export const FETCH_START = "FETCH_START";
export const FETCH_COMPLETE = "FETCH_COMPLETE";
export const FETCH_FAILED = "FETCH_FAILED"; 

export const ADD_START = "ADD_START";
export const ADD_COMPLETE = "ADD_COMPLETE";
export const ADD_FAILED = "ADD_FAILED"; 

export const DELETE_START = "DELETE_START";
export const DELETE_COMPLETE = "DELETE_COMPLETE";
export const DELETE_FAILED = "DELETE_FAILED"; 

export const UPDATE_START = "UPDATE_START";
export const UPDATE_COMPLETE = "UPDATE_COMPLETE";
export const UPDATE_FAILED = "UPDATE_FAILED"; 